[2022-12-17T06:02:46.375+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-16T14:51:25.691090+00:00 [queued]>
[2022-12-17T06:02:46.485+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-16T14:51:25.691090+00:00 [queued]>
[2022-12-17T06:02:46.489+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T06:02:46.490+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 5
[2022-12-17T06:02:46.491+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T06:02:46.691+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2022-12-16 14:51:25.691090+00:00
[2022-12-17T06:02:46.760+0000] {standard_task_runner.py:55} INFO - Started process 1216 to run task
[2022-12-17T06:02:46.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_with_***', 'create_table_task', 'manual__2022-12-16T14:51:25.691090+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp85sqr3wu']
[2022-12-17T06:02:46.832+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask create_table_task
[2022-12-17T06:02:47.386+0000] {task_command.py:389} INFO - Running <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-16T14:51:25.691090+00:00 [running]> on host 0d1c0c89de6a
[2022-12-17T06:02:48.211+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_with_***
AIRFLOW_CTX_TASK_ID=create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T14:51:25.691090+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T14:51:25.691090+00:00
[2022-12-17T06:02:48.237+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE traffic_data (id INT NOT NULL, track_id INT NOT NULL, type VARCHAR(250) NOT NULL, traveled_d VARCHAR(250) NOT NULL, avg_speed VARCHAR(250) NOT NULL, lat VARCHAR(250) NOT NULL, lon VARCHAR(250) NOT NULL, speed VARCHAR(250) NOT NULL, lon_acc VARCHAR(250) NOT NULL, lat_acc VARCHAR(250) NOT NULL, time VARCHAR(250) NOT NULL);
        
[2022-12-17T06:02:48.406+0000] {base.py:73} INFO - Using connection ID '***_dbt_setup' for task execution.
[2022-12-17T06:04:40.906+0000] {base.py:73} INFO - Using connection ID '***_dbt_setup' for task execution.
[2022-12-17T06:04:41.074+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  database "***_dbt " does not exist

[2022-12-17T06:04:41.322+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=postgres_with_***, task_id=create_table_task, execution_date=20221216T145125, start_date=20221217T060246, end_date=20221217T060441
[2022-12-17T06:04:41.757+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 42 for task create_table_task (connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  database "***_dbt " does not exist
; 1216)
[2022-12-17T06:04:42.012+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T06:04:42.282+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
